name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Setup Node.js 22 LTS
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: TypeScript type checking
      run: npx tsc --noEmit
      
    - name: Lint code
      run: |
        npm install eslint --no-save
        npx eslint . --ext .js,.jsx,.ts,.tsx
      
    - name: Run tests
      run: |
        if [ -f "package.json" ] && grep -q "\"test\"" package.json; then
          npm test
        else
          echo "No test script found in package.json, skipping tests"
        fi
      
    - name: Cache Expo dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
      
    # - name: Build Expo web
    #   run: |
    #     if grep -q "\"web\"" package.json; then
    #       npx expo export:web
    #     else
    #       echo "Web build not configured, skipping"
    #     fi