name: Deploy to Expo

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Expo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js 22 LTS
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Verify TypeScript
        run: npx tsc --noEmit

      - name: Publish to Expo
        run: |
          npx expo-cli login -u ${{ secrets.EXPO_USERNAME }} -p ${{ secrets.EXPO_PASSWORD }}
          npx expo-cli publish --non-interactive

      - name: Create Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          body: |
            Release v${{ github.run_number }}
            
            Changes in this Release:
            ${{ github.event.head_commit.message }}
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false